services:
  db:
    image: postgres:16
    container_name: zaria_db
    environment:
      POSTGRES_USER: zaria
      POSTGRES_PASSWORD: zaria
      POSTGRES_DB: zaria
    ports:
      - "5432:5432"
    volumes:
      - zaria_pg:/var/lib/postgresql/data

volumes:
  zaria_pg:
